### PR TITLE
fix: theme switching on linux

### LINKED ISSUE #178: Linux: switching themes fails when starting in dark mode
To reproduce:

- run app from dark theme so it starts in dark mode
- switch to white theme -> see app only changing some parts of the UI, not all

When doing it the other way around it works as expected (staring in light mode and switching to dark)

### PR DESCRIPTION
**Pull request by ilge-ustun**
Closes https://github.com/gnosis/gnosis_vpn-app/issues/178

### CODE REVIEW

**Review by esterlus — CHANGES_REQUESTED** [review]
Fixes the issue.

But adds too many dependencies in the process and some arbitrary timeouts.

Let's try to leverage tauri tokio runtime for threading/async tasks

File: src/index.tsx [hunk 1]
```diff
@@ -31,37 +31,74 @@ function applyTheme(theme: string) {
...
+          unlistenTauri?.();
+          unlistenLinux?.();
         };
       };
-      initTheme();
+
+      initTheme().then((c) => {
+        if (disposed) c();
+        else cleanup = c;
+      });
```
[the remark this answers is not in the document]
Comment (ilge-ustun) [reply src/index.tsx:110]: initTheme is structured to never reject, all 4 async operations each have their own try/catch, and nothing between them can throw. The .catch was intentionally removed as dead code

File: src/index.tsx [hunk 2]
```diff
@@ -31,37 +31,74 @@ function applyTheme(theme: string) {
...
+          applyTheme(initial);
+        } catch (e) {
+          console.error("[theme] initial theme fetch failed", e);
+        }
+
+        // Each block is isolated so a failure in one does not skip the others.
+        try {
+          const mq = globalThis.matchMedia("(prefers-color-scheme: dark)");
+          // Apply current value as fallback in case get_initial_theme failed or is stale.
+          applyTheme(mq.matches ? "dark" : "light");
```
Comment (esterlus) [inline src/index.tsx]: If the previous `get_initial_theme` query succeeds and applies the correct theme, that this either does the same or overrides it with adifferent theme.

It would be better to first determine the theme with whatever method you deem fit. Or both of them.
And then apply it once.

File: src/index.tsx [hunk 3]
```diff
@@ -31,37 +31,74 @@ function applyTheme(theme: string) {
...
+        } catch (e) {
+          console.error("[theme] onThemeChanged setup failed", e);
+        }
 
-        unlisten = () => {
-          unlistenTauri();
-          unlistenLinux();
+        // Linux: backend emits "os-theme-changed" via XDG Desktop Portal / gsettings fallback.
+        try {
+          unlistenLinux = await listen<string>(
```
Comment (esterlus) [inline src/index.tsx:88]: both macos and Linux listeners are set up unconditionally. don't know if that is necessary.

File: src/index.tsx [hunk 4]
```diff
@@ -31,37 +31,74 @@ function applyTheme(theme: string) {
...
+            ({ payload: theme }) => {
+              applyTheme(theme);
+            },
+          );
+        } catch (e) {
+          console.error("[theme] os-theme-changed listener setup failed", e);
+        }
+
+        return () => {
+          mqCleanup?.();
```
Comment (esterlus) [inline src/index.tsx]: All of those values are set up in the fucntion, so why make the optionally undefined?

File: src/index.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (esterlus) [reply src/index.tsx:110]: Add a comment describing this intentional behavior

**Review by esterlus — CHANGES_REQUESTED** [review]

File: src/index.tsx (hunk 3 above)
Comment (ilge-ustun) [reply src/index.tsx:88]: Kept unconditional to avoid a runtime OS check for no functional gain

**Review by esterlus — APPROVED** [review]

**Comment by esterlus** [comment]
We can ignore the failing deno audit. Seems related to npm changing their API response: 
https://github.com/denoland/deno/issues/33287
